### ISSUE TITLE
Do the server tools work with non-Xserve Macs?

### ISSUE THREAD

**Issue by crsleeth** [abdyfranco/xserve-reloaded#1]
I'm trying out the server tools on a Mac Mini running High Sierra but am unable to get them to launch. Is there anything I need to do with the pkgproj file?

**Comment by abdyfranco** [comment]
No, the Server Tools are explicitly tied to the specific Xserve hardware. It doesn't work on any other Mac.

**Comment by crsleeth** [comment]
Unfortunately I can't get the server apps to work with Xserves either. Currently the attached picture shows an Xserve on El Capitan.
![screen shot 2018-06-20 at 1 58 27 pm](https://user-images.githubusercontent.com/13802587/41675955-23cd3c46-7492-11e8-9f32-fa1079fb414f.png)

**Comment by abdyfranco** [comment]
Before using the Server Tools, you must compile it using the [Packages](http://s.sudre.free.fr/Software/Packages/about.html) application.
This is because these applications require various components and kext installed in the system.

**Comment by abdyfranco** [comment]
I have tested the applications in High Sierra and it is indeed a bug, please check the last commit in which the problem is already fixed.
